export default function (context, models) {
  models
  .forEach(model => {
    context.strokeStyle = '#0095d9'

    context.save()
    context.translate(model.x[1], model.y[1])
    context.rotate(Math.PI / 2 + model.rots[1])
    context.beginPath()
    context.lineTo(-4, -2)
    context.lineTo(4, -2)
    context.stroke()
    context.beginPath()
    context.lineTo(0, -14)
    context.lineTo(-6, -6)
    context.lineTo(6, -6)
    context.closePath()
    context.stroke()
    context.restore()

    context.save()
    context.translate(model.x[1], model.y[1])
    context.rotate(Math.PI / 2 + model.rots[1])
    context.beginPath()
    context.lineTo(14, 16)
    context.lineTo(12, 8)
    context.lineTo(8, 6)
    context.closePath()
    context.stroke()
    context.restore()

    context.save()
    context.translate(model.x[1], model.y[1])
    context.rotate(Math.PI / 2 + model.rots[1])
    context.beginPath()
    context.lineTo(-14, 16)
    context.lineTo(-12, 8)
    context.lineTo(-8, 6)
    context.closePath()
    context.stroke()
    context.restore()

    context.save()
    context.translate(model.x[2], model.y[2])
    context.rotate(Math.PI / 2 + model.rots[2])
    context.beginPath()
    context.lineTo(-4, 0)
    context.lineTo(4, 0)
    context.stroke()
    context.restore()

    context.save()
    context.translate(model.x[3], model.y[3])
    context.rotate(Math.PI / 2 + model.rots[3])
    context.beginPath()
    context.lineTo(-4, 0)
    context.lineTo(4, 0)
    context.stroke()
    context.restore()

    context.save()
    context.translate(model.x[4], model.y[4])
    context.rotate(Math.PI / 2 + model.rots[4])
    context.beginPath()
    context.lineTo(-4, -2)
    context.lineTo(4, -2)
    context.stroke()
    context.restore()

    context.save()
    context.translate(model.x[5], model.y[5])
    context.rotate(Math.PI / 2 + model.rots[5])
    context.beginPath()
    context.lineTo(-6, -2)
    context.lineTo(5, -2)
    context.stroke()
    context.restore()

    context.save()
    context.translate(model.x[6], model.y[6])
    context.rotate(Math.PI / 2 + model.rots[6])
    context.beginPath()
    context.lineTo(-5, 0)
    context.lineTo(5, 0)
    context.stroke()
    context.restore()

    context.save()
    context.translate(model.x[8], model.y[8])
    context.rotate(Math.PI / 2 + model.rots[8])
    context.beginPath()
    context.lineTo(-2, 0)
    context.lineTo(2, 0)
    context.stroke()
    context.restore()

    context.save()
    context.translate(model.x[9], model.y[9])
    context.rotate(Math.PI / 2 + model.rots[9])
    context.beginPath()
    context.lineTo(0, 0)
    context.lineTo(4, 4)
    context.stroke()
    context.beginPath()
    context.lineTo(0, 0)
    context.lineTo(-4, 4)
    context.stroke()
    context.restore()
  })
}
